name: Bug report
description: File a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you saw.
      placeholder: A bug happened!
    validations:
      required: true